## Why R ?

### Accessibility

* easy to learn even for non-statistician/data scientist

### Packages manager

* more than 13,000 community-based libraries
* cutting-edges statistical methods

### Reproducibility

* Rmarkdown is not just a notebook
* Great for interfacing, plotting, making scientific reports
* R dev/package well integrated on [github](https://github.com), [binder](http://mybinder.org)

### The community

* CRAN community [https://cran.r-project.org/](https://cran.r-project.org/)
* Rstudio community [https://community.rstudio.com/](https://community.rstudio.com/)
* SatRDay, R user groups, meet-up, conferences, Twitter


## Why not R?

### Some limitations

- Easy to write dirty (unreadable) code

- Easy to write inefficient code

- Many useless packages

- Not a typed language and no compilation by default: may be slow

- Many ways to do the same things

- Less well interfaced to GAFAM ML/Deep-learning libraries than Python

## So why R again?

### The Rstudio group

Even if it is a company...

&nbsp; 

- Rstudio IDE is a great all-in-one tool for data analysis and development

- Towards cleaner/consistent implementation (\texttt{tidyverse} and co)

- Many features from computer science (unitary test, github integration)  

- Enhanced interfaces to ML/DL tools (Tensor Flow, Keras, Torch, etc.)  

- Great interface with with Python (package \texttt{reticulate})

### The \C{R} community

- CRAN taskviews and \texttt{R} foundation

- Great interface with with \texttt{C++} (packages \texttt{Rcpp}, \texttt{RcppArmadillo})

- Nice surrogate Oriented-Object programming with R6 

&nbsp; 

\rsa These features basically saved \C{R} (for how long?) 

