---
title: (A bit of) Advanced R
subtitle: Efficient `R` programming
author: Julien Chiquet
institute: Université Paris Dauphine
date: "Juin 2018"
csl: "../resources/apa-no-doi-no-issue.csl"
output:
  beamer_presentation:
    slide_level: 2
    highlight: tango
    includes: 
      in_header: ../resources/common_preamble.tex
      before_body: ../resources/common_startup.tex
bibliography: ../resources/bibliography.bib
fontsize: 10pt
---

```{r setup, child="../resources/knitr_setup.Rmd", include = FALSE}
```

## Resources

- @efficientR: efficient R programming
- @advr

# Benchmark your code

```{r child_microbenchmark, child="../Rmd_files/profiling/microbenchmark.Rmd"}
```

```{r child_profiling, child="../Rmd_files/profiling/profr.Rmd"}
```

# Use all your cores when needed

```{r child_intro_parallel, child="../Rmd_files/parallel_computing/intro_parallel_computing.Rmd"}
```

```{r child_parellel, child="../Rmd_files/parallel_computing/parallel.Rmd"}
```

# Good and bad practices in `R`

```{r child_vectorize, child="../Rmd_files/good_bad_practices/vectorize.Rmd"}
```

```{r child_compilation, child="../Rmd_files/good_bad_practices/compilation.Rmd"}
```

```{r child_growing, child="../Rmd_files/good_bad_practices/growing.Rmd"}
```

# Tricks

```{r child_internal, child="../Rmd_files/tricks/internal.Rmd"}
```

```{r child_use_algebra, child="../Rmd_files/tricks/use_algebra.Rmd"}
```

# Remember that R is object oriented

```{r child_factor, child="../Rmd_files/good_bad_practices/factors.Rmd"}
```

```{r child_float, child="../Rmd_files/good_bad_practices/float.Rmd"}
```

```{r child_order, child="../Rmd_files/good_bad_practices/order.Rmd"}
```

# Mind your vocabulary: `R` fast built in function

```{r child_colSums, child="../Rmd_files/vocabulary/colSums_family.Rmd"}
```

```{r child_rowsum, child="../Rmd_files/vocabulary/rowsum.Rmd"}
```

```{r child_algebra, child="../Rmd_files/vocabulary/algebra.Rmd"}
```

```{r child_Matrix, child="../Rmd_files/vocabulary/Matrix.Rmd"}
```

# Interface with lower-level languages

```{r child_RcppExample1, child="../Rmd_files/Rcpp/RcppArmadillo.Rmd"}
```

```{r child_RcppExample2, child="../Rmd_files/Rcpp/RcppArmadillo2.Rmd"}
```

## References
